-- Seed data ported from frontend/src/App.tsx (jPrime conference).
-- Generated; conference reference data only (no per-device user data).

insert into conference_day (id, weekday, wd_short, date_label, short_label, calendar_date) values
  (1, 'Wednesday', 'Wed', 'June 3, 2026', 'Jun 3', date '2026-06-03'),
  (2, 'Thursday', 'Thu', 'June 4, 2026', 'Jun 4', date '2026-06-04'),
  (3, 'Friday', 'Fri', 'June 5, 2026', 'Jun 5', date '2026-06-05');

insert into room (name) values
  ('Hall A'),
  ('Hall B'),
  ('Atrium');

insert into map_spot (name, pos_x, pos_y, kind, sort_order) values
  ('Hall A', '18%', '22%', 'stage', 0),
  ('Hall B', '63%', '24%', 'stage', 1),
  ('Hall C', '22%', '61%', 'stage', 2),
  ('Booths', '66%', '62%', 'booth', 3),
  ('Coffee', '44%', '44%', 'coffee', 4);

insert into speaker (name, role, org, location, pronoun, bio, handle) values
  ('Venkat Subramaniam', 'Award-winning author & founder', 'Agile Developer, Inc.', 'Chicago, US', 'he/him', 'Venkat has trained and mentored thousands of developers across five continents and authored a shelf of books on the JVM, functional programming, and pragmatic agility. On stage he turns dense platform internals into something you can actually use on Monday morning.', '@venkat_s'),
  ('Maya Petrova', 'Principal Engineer', 'Sofia AI Labs', 'Sofia, BG', 'she/her', 'Maya builds the integration layers that sit between large models and production Java services. She cares about boring reliability — backpressure, idempotency, graceful degradation — and the records-and-virtual-threads toolkit that makes it readable.', '@maya.codes'),
  ('Nikolay Ivanov', 'Staff Platform Engineer', 'CloudForge', 'Plovdiv, BG', 'he/him', 'Nikolay has spent a decade keeping JVM workloads honest on Kubernetes. He speaks from the scars of midnight pages: probes that lie, memory limits that surprise, and the deploy habits that make services boring in the best way.', '@nikolay.k8s'),
  ('Elena Markova', 'Lead Backend Architect', 'Northwind Bank', 'Varna, BG', 'she/her', 'Elena designs APIs that have to survive a decade of regulation, reorgs, and rewrites. Her talks are a field guide to versioning, contracts, and the small decisions that decide whether a service ages gracefully or rots.', '@elena.api'),
  ('Victor Stoyanov', 'Performance Engineer', 'Helix Trading', 'London, UK', 'he/him', 'Victor lives in flame graphs. From low-latency trading paths he brings a profiler-first mindset: measure, don''t guess, and respect the allocation. Expect live JFR recordings and a few uncomfortable truths about your hot loop.', '@vstoyanov'),
  ('Iva Georgieva', 'Developer Advocate', 'Quarkus Community', 'Berlin, DE', 'she/her', 'Iva translates between the framework maintainers and the people shipping with them. She runs hands-on workshops where the goal is that everyone leaves with code that compiled — not just slides they screenshotted.', '@iva.dev'),
  ('Georgi Dimitrov', 'Security Engineer', 'Sentinel Security', 'Sofia, BG', 'he/him', 'Georgi breaks Java apps so the audience doesn''t have to learn the hard way. His sessions walk the supply chain end to end — dependencies, secrets, and the defaults that quietly betray you in production.', '@gdimitrov.sec'),
  ('Daniela Koleva', 'Data Engineering Lead', 'Streamline Analytics', 'Burgas, BG', 'she/her', 'Daniela moves billions of events a day through JVM stream processors and still sleeps at night. She''ll show the schema discipline and replay strategies that keep a pipeline trustworthy when the data inevitably misbehaves.', '@daniela.streams'),
  ('Stefan Petrov', 'Engineering Manager', 'Mosaic Software', 'Sofia, BG', 'he/him', 'Stefan leads teams that have to balance feature velocity with a codebase they want to keep. He talks candidly about technical debt, refactoring under pressure, and the human side of keeping Java systems maintainable.', '@stefan.builds');

insert into speaker_tag (speaker_id, tag, sort_order) values
  ((select id from speaker where name = 'Venkat Subramaniam'), 'JVM internals', 0),
  ((select id from speaker where name = 'Venkat Subramaniam'), 'Functional Java', 1),
  ((select id from speaker where name = 'Venkat Subramaniam'), 'Concurrency', 2),
  ((select id from speaker where name = 'Venkat Subramaniam'), 'Teaching', 3),
  ((select id from speaker where name = 'Maya Petrova'), 'AI assistants', 0),
  ((select id from speaker where name = 'Maya Petrova'), 'Virtual threads', 1),
  ((select id from speaker where name = 'Maya Petrova'), 'Records', 2),
  ((select id from speaker where name = 'Maya Petrova'), 'Reliability', 3),
  ((select id from speaker where name = 'Nikolay Ivanov'), 'Kubernetes', 0),
  ((select id from speaker where name = 'Nikolay Ivanov'), 'Observability', 1),
  ((select id from speaker where name = 'Nikolay Ivanov'), 'GraalVM', 2),
  ((select id from speaker where name = 'Nikolay Ivanov'), 'SRE', 3),
  ((select id from speaker where name = 'Elena Markova'), 'API design', 0),
  ((select id from speaker where name = 'Elena Markova'), 'Spring Boot', 1),
  ((select id from speaker where name = 'Elena Markova'), 'Domain modeling', 2),
  ((select id from speaker where name = 'Elena Markova'), 'Longevity', 3),
  ((select id from speaker where name = 'Victor Stoyanov'), 'JIT', 0),
  ((select id from speaker where name = 'Victor Stoyanov'), 'Profiling', 1),
  ((select id from speaker where name = 'Victor Stoyanov'), 'Low latency', 2),
  ((select id from speaker where name = 'Victor Stoyanov'), 'GC tuning', 3),
  ((select id from speaker where name = 'Iva Georgieva'), 'Quarkus', 0),
  ((select id from speaker where name = 'Iva Georgieva'), 'DevRel', 1),
  ((select id from speaker where name = 'Iva Georgieva'), 'Workshops', 2),
  ((select id from speaker where name = 'Iva Georgieva'), 'Native images', 3),
  ((select id from speaker where name = 'Georgi Dimitrov'), 'AppSec', 0),
  ((select id from speaker where name = 'Georgi Dimitrov'), 'Supply chain', 1),
  ((select id from speaker where name = 'Georgi Dimitrov'), 'Dependencies', 2),
  ((select id from speaker where name = 'Georgi Dimitrov'), 'Threat modeling', 3),
  ((select id from speaker where name = 'Daniela Koleva'), 'Kafka', 0),
  ((select id from speaker where name = 'Daniela Koleva'), 'Stream processing', 1),
  ((select id from speaker where name = 'Daniela Koleva'), 'Schemas', 2),
  ((select id from speaker where name = 'Daniela Koleva'), 'Data quality', 3),
  ((select id from speaker where name = 'Stefan Petrov'), 'Architecture', 0),
  ((select id from speaker where name = 'Stefan Petrov'), 'Tech debt', 1),
  ((select id from speaker where name = 'Stefan Petrov'), 'Leadership', 2),
  ((select id from speaker where name = 'Stefan Petrov'), 'Refactoring', 3);

insert into notification (id, kind, title, body, time_label, unread, sort_order) values
  ('n1', 'reminder', 'Starting in 10 minutes', 'Java 25: Patterns for Useful AI Assistants · Hall A', 'now', true, 0),
  ('n2', 'alert', 'Room change', 'Spring Boot APIs That Age Well moves to Hall A at 10:40.', '8m', true, 1),
  ('n3', 'info', 'Lunch relocated', 'Lunch boxes move to the Atrium after 12:25. Workshop rooms stay on level 2.', '22m', false, 2);

insert into rating_criterion (name, sort_order) values
  ('Content', 0),
  ('Speaker', 1),
  ('Practical value', 2),
  ('Pace', 3);

insert into session (id, day_id, start_time, end_time, title, room_id, track, level, kind, plenary, description, status, sort_order) values
  ('k1', 1, time '09:00', time '09:25', 'Opening Keynote: Java''s Next Decade', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'A wide-angle look at where the platform is heading — language ergonomics, the runtime, and the habits that keep Java teams productive over the next decade.', 'done', 1),
  ('s1', 1, time '09:30', time '10:20', 'Java 25: Patterns for Useful AI Assistants', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'A practical tour of modern Java features for building reliable assistant workflows, including records, virtual threads, structured concurrency, and safer integration boundaries.', 'live', 2),
  ('s2', 1, time '09:30', time '10:20', 'Cloud Native Java on Kubernetes', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'A pragmatic look at packaging, probes, memory limits, and deploy habits that make JVM services behave predictably in Kubernetes.', 'live', 3),
  ('b1', 1, time '10:20', time '10:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Refuel and meet the sponsor booths in the Atrium.', 'upcoming', 4),
  ('s3', 1, time '10:40', time '11:30', 'Spring Boot APIs That Age Well', (select id from room where name = 'Hall A'), 'Track 1', 'Beginner', 'lecture', false, 'Endpoint shapes, versioning habits, and validation details that keep public and internal APIs understandable as products evolve.', 'upcoming', 5),
  ('s4', 1, time '10:40', time '11:30', 'Production Observability Without Dashboard Fatigue', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Design logs, traces, and alerts that help teams act during real incidents instead of creating another wall of red charts.', 'upcoming', 6),
  ('s5', 1, time '11:45', time '12:25', 'Workshop: Fast Feedback Loops for JVM Teams', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'A hands-on look at test slicing, build profiling, and local environments that keep Java teams moving without lowering quality.', 'upcoming', 7),
  ('s6', 1, time '11:45', time '12:25', 'Modular Architecture for Busy Java Teams', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'How to introduce module boundaries, package rules, and team-owned APIs inside a mature Java codebase without pausing delivery.', 'upcoming', 8),
  ('l1', 1, time '12:25', time '13:20', 'Lunch', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Lunch boxes are served in the Atrium. Workshop rooms stay open on level 2.', 'upcoming', 9),
  ('s7', 1, time '13:20', time '14:10', 'Virtual Threads in Practice', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Where virtual threads shine, where they don''t, and how to migrate blocking code without surprising your thread pools.', 'upcoming', 10),
  ('s8', 1, time '13:20', time '14:10', 'Event-Driven Systems with Kafka and Java', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Designing resilient event flows — partitioning, idempotency, and the consumer habits that keep streaming pipelines healthy.', 'upcoming', 11),
  ('s9', 1, time '14:20', time '15:10', 'Workshop: Testing Strategies That Scale', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'Hands-on patterns for fast, trustworthy test suites — test pyramids, contract tests, and pragmatic mocking.', 'upcoming', 12),
  ('s10', 1, time '14:20', time '15:10', 'JVM Performance Tuning Myths', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Separating the GC folklore from the measurements that actually move latency and throughput in production.', 'upcoming', 13),
  ('b2', 1, time '15:10', time '15:30', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Afternoon coffee and sponsor booths in the Atrium.', 'upcoming', 14),
  ('s11', 1, time '15:30', time '16:20', 'Records, Sealed Types, and Pattern Matching', (select id from room where name = 'Hall A'), 'Track 1', 'Beginner', 'lecture', false, 'Modeling data with modern Java language features for clearer, safer, and more maintainable domain code.', 'upcoming', 15),
  ('s12', 1, time '15:30', time '16:20', 'Securing Java Microservices', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Practical auth, secrets handling, and dependency hygiene for service meshes built on the JVM.', 'upcoming', 16),
  ('s13', 1, time '16:30', time '17:20', 'Data Access with Spring Data and JPA', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Mapping habits, query tuning, and the N+1 traps that quietly slow down data-heavy Java applications.', 'upcoming', 17),
  ('s14', 1, time '16:30', time '17:20', 'Reactive Java: When and Why', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'A grounded look at reactive programming trade-offs and how it compares to virtual threads for concurrency.', 'upcoming', 18),
  ('b3', 1, time '17:20', time '17:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Last break of the day — grab a drink before the closing sessions.', 'upcoming', 19),
  ('s15', 1, time '17:40', time '18:30', 'Building Developer Tools with Java', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Lessons from building CLIs, plugins, and code generators that developers actually enjoy using.', 'upcoming', 20),
  ('s16', 1, time '17:40', time '18:30', 'From Monolith to Modular Monolith', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'A migration story — extracting boundaries and team ownership without a risky big-bang rewrite.', 'upcoming', 21),
  ('k2', 1, time '18:30', time '19:00', 'Closing Keynote: The Joy of Shipping Java', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'A closing reflection on craft, community, and the everyday habits that make shipping Java a genuinely enjoyable practice.', 'upcoming', 22),
  ('d2-k1', 2, time '09:00', time '09:25', 'Keynote: Inside the Modern JVM', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'A guided tour under the hood — how the JIT, garbage collectors, and recent runtime projects quietly shape the performance of every Java application you ship.', 'upcoming', 1),
  ('d2-s1', 2, time '09:30', time '10:20', 'Project Leyden: Faster Startup, Smaller Footprint', (select id from room where name = 'Hall A'), 'Track 1', 'Advanced', 'lecture', false, 'Where ahead-of-time work is heading in the JDK and what Leyden''s condensers mean for startup time, warmup, and the shape of future deployments.', 'upcoming', 2),
  ('d2-s2', 2, time '09:30', time '10:20', 'GraalVM Native Image in Production', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Reflection config, build-time initialization, and the operational trade-offs of shipping native binaries instead of fat JARs.', 'upcoming', 3),
  ('d2-b1', 2, time '10:20', time '10:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Refuel and meet the sponsor booths in the Atrium.', 'upcoming', 4),
  ('d2-s3', 2, time '10:40', time '11:30', 'Structured Concurrency Beyond the Basics', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Cancellation, scoped values, and error propagation patterns that make concurrent Java read like sequential code without the foot-guns.', 'upcoming', 5),
  ('d2-s4', 2, time '10:40', time '11:30', 'Taming the G1 and ZGC Collectors', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'A practical comparison of modern collectors — pause goals, heap sizing, and the telemetry you need before touching a single GC flag.', 'upcoming', 6),
  ('d2-s5', 2, time '11:45', time '12:25', 'Workshop: Profiling with JFR and async-profiler', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'Hands-on flame graphs — capture a JFR recording, read allocation and lock profiles, and turn the findings into a concrete fix.', 'upcoming', 7),
  ('d2-s6', 2, time '11:45', time '12:25', 'The Foreign Function & Memory API in Anger', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Calling native libraries and managing off-heap memory safely with the Panama APIs, and when the complexity actually pays off.', 'upcoming', 8),
  ('d2-l1', 2, time '12:25', time '13:20', 'Lunch', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Lunch boxes are served in the Atrium. Workshop rooms stay open on level 2.', 'upcoming', 9),
  ('d2-s7', 2, time '13:20', time '14:10', 'Scaling Postgres Access from the JVM', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Connection pools, prepared-statement caches, and the access patterns that keep a busy Java service from overwhelming its database.', 'upcoming', 10),
  ('d2-s8', 2, time '13:20', time '14:10', 'Resilient gRPC Services in Java', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Deadlines, retries, and backoff for service-to-service calls — the resilience details that decide how a mesh behaves under load.', 'upcoming', 11),
  ('d2-s9', 2, time '14:20', time '15:10', 'Workshop: Building a Native CLI with GraalVM', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'Build a fast-starting command-line tool from a Java codebase, compile it to a native binary, and ship it as a single executable.', 'upcoming', 12),
  ('d2-s10', 2, time '14:20', time '15:10', 'Caching Strategies That Don''t Bite Back', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Invalidation, stampede protection, and the cache-shape decisions that keep a speed optimization from becoming a correctness bug.', 'upcoming', 13),
  ('d2-b2', 2, time '15:10', time '15:30', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Afternoon coffee and sponsor booths in the Atrium.', 'upcoming', 14),
  ('d2-s11', 2, time '15:30', time '16:20', 'Memory Leaks: A Field Investigation', (select id from room where name = 'Hall A'), 'Track 1', 'Advanced', 'lecture', false, 'A whodunnit through heap dumps and dominator trees — how to find what''s holding references it shouldn''t, on a live JVM.', 'upcoming', 15),
  ('d2-s12', 2, time '15:30', time '16:20', 'Schema Evolution for Event Streams', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Compatibility rules, registries, and migration habits that let Kafka topics evolve without breaking every consumer downstream.', 'upcoming', 16),
  ('d2-s13', 2, time '16:30', time '17:20', 'Designing for Backpressure', (select id from room where name = 'Hall A'), 'Track 1', 'Advanced', 'lecture', false, 'What happens when producers outrun consumers, and the bounded queues, rate limits, and load-shedding that keep systems standing.', 'upcoming', 17),
  ('d2-s14', 2, time '16:30', time '17:20', 'Zero-Downtime Database Migrations', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Expand-and-contract schema changes, backfills, and dual writes that let you reshape tables without a maintenance window.', 'upcoming', 18),
  ('d2-b3', 2, time '17:20', time '17:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Last break of the day — grab a drink before the closing sessions.', 'upcoming', 19),
  ('d2-s15', 2, time '17:40', time '18:30', 'GraalVM Polyglot: Mixing Java and Beyond', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Embedding scripting languages inside JVM applications with the polyglot APIs, and where the boundary costs show up.', 'upcoming', 20),
  ('d2-s16', 2, time '17:40', time '18:30', 'Observability for Native Images', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Metrics, tracing, and heap insight when there''s no JVM agent to attach — instrumenting GraalVM binaries in production.', 'upcoming', 21),
  ('d2-k2', 2, time '18:30', time '19:00', 'Keynote: Performance Is a Feature', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'A closing argument for treating latency and footprint as product features, with the measurement habits that keep performance from quietly eroding release after release.', 'upcoming', 22),
  ('d3-k1', 3, time '09:00', time '09:25', 'Keynote: The Architecture of Tomorrow''s Java', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'How language features, AI tooling, and modular thinking are reshaping the way we structure Java systems — and the principles that stay constant underneath.', 'upcoming', 1),
  ('d3-s1', 3, time '09:30', time '10:20', 'Hexagonal Architecture, Pragmatically', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Ports, adapters, and where the dogma helps versus hurts — a grounded take on keeping business logic free of framework gravity.', 'upcoming', 2),
  ('d3-s2', 3, time '09:30', time '10:20', 'LLM-Assisted Code Review for Java Teams', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Where AI review genuinely catches issues, where it hallucinates, and how to wire it into a pull-request workflow without slowing teams down.', 'upcoming', 3),
  ('d3-b1', 3, time '10:20', time '10:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Refuel and meet the sponsor booths in the Atrium.', 'upcoming', 4),
  ('d3-s3', 3, time '10:40', time '11:30', 'Domain-Driven Design Without the Dogma', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Aggregates, bounded contexts, and ubiquitous language explained through code you''d actually merge, not a 600-page ceremony.', 'upcoming', 5),
  ('d3-s4', 3, time '10:40', time '11:30', 'Embedding AI Models in JVM Services', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'Running and serving models from Java — batching, timeouts, and the integration boundaries that keep an inference call from sinking a request.', 'upcoming', 6),
  ('d3-s5', 3, time '11:45', time '12:25', 'Workshop: Refactoring Legacy Java Safely', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'Characterization tests, seams, and small safe steps — practice taming a gnarly class without a rewrite and without fear.', 'upcoming', 7),
  ('d3-s6', 3, time '11:45', time '12:25', 'Contract Testing Across Teams', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Consumer-driven contracts that let independent services evolve without a fragile wall of end-to-end tests holding everyone hostage.', 'upcoming', 8),
  ('d3-l1', 3, time '12:25', time '13:20', 'Lunch', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Lunch boxes are served in the Atrium. Workshop rooms stay open on level 2.', 'upcoming', 9),
  ('d3-s7', 3, time '13:20', time '14:10', 'Property-Based Testing in Java', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'lecture', false, 'Let the framework invent the edge cases — generators, shrinking, and the invariants that catch bugs example tests never reach.', 'upcoming', 10),
  ('d3-s8', 3, time '13:20', time '14:10', 'Securing the Software Supply Chain', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'SBOMs, signed artifacts, and dependency provenance — closing the gaps attackers use between your build and your users.', 'upcoming', 11),
  ('d3-s9', 3, time '14:20', time '15:10', 'Workshop: Build Pipelines Developers Trust', (select id from room where name = 'Hall A'), 'Track 1', 'Intermediate', 'workshop', false, 'Hands-on CI design — caching, parallelism, and flaky-test triage that turn a slow red pipeline into one teams actually believe.', 'upcoming', 12),
  ('d3-s10', 3, time '14:20', time '15:10', 'Threat Modeling for Java Services', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'A lightweight, repeatable way to find the attacks that matter before code review, mapped to concrete JVM-side mitigations.', 'upcoming', 13),
  ('d3-b2', 3, time '15:10', time '15:30', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Afternoon coffee and sponsor booths in the Atrium.', 'upcoming', 14),
  ('d3-s11', 3, time '15:30', time '16:20', 'The Art of the Code Review', (select id from room where name = 'Hall A'), 'Track 1', 'Beginner', 'lecture', false, 'Reviews that teach instead of gatekeep — tone, scope, and the small habits that make a team''s pull requests something people enjoy.', 'upcoming', 15),
  ('d3-s12', 3, time '15:30', time '16:20', 'Feature Flags and Progressive Delivery', (select id from room where name = 'Hall B'), 'Track 2', 'Intermediate', 'lecture', false, 'Decoupling deploy from release — flag hygiene, gradual rollouts, and the cleanup discipline that stops flags from becoming debt.', 'upcoming', 16),
  ('d3-s13', 3, time '16:30', time '17:20', 'Documentation Developers Actually Read', (select id from room where name = 'Hall A'), 'Track 1', 'Beginner', 'lecture', false, 'READMEs, ADRs, and runbooks that earn their keep — writing the few documents teammates open instead of the many they ignore.', 'upcoming', 17),
  ('d3-s14', 3, time '16:30', time '17:20', 'Migrating to the Java Module System', (select id from room where name = 'Hall B'), 'Track 2', 'Advanced', 'lecture', false, 'A staged path onto JPMS in a real codebase — split packages, automatic modules, and the strong encapsulation payoff at the end.', 'upcoming', 18),
  ('d3-b3', 3, time '17:20', time '17:40', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Last break of the day — grab a drink before the closing sessions.', 'upcoming', 19),
  ('d3-s15', 3, time '17:40', time '18:30', 'Open Source: From Contributor to Maintainer', (select id from room where name = 'Hall A'), 'Track 1', 'Beginner', 'lecture', false, 'How to make a first pull request land, earn trust over time, and eventually carry the keys — the human path through an OSS project.', 'upcoming', 20),
  ('d3-s16', 3, time '17:40', time '18:30', 'Career Growth for Senior Engineers', (select id from room where name = 'Hall B'), 'Track 2', 'All levels', 'lecture', false, 'Beyond the senior title — scope, influence, and technical leadership without being pushed into management you didn''t ask for.', 'upcoming', 21),
  ('d3-k2', 3, time '18:30', time '19:00', 'Closing Keynote: Community, Craft, and What''s Next', (select id from room where name = 'Hall A'), 'Plenary', 'All levels', 'keynote', true, 'A warm send-off about the people behind the platform — mentorship, open source, and the everyday craft that keeps the Java community thriving.', 'upcoming', 22);

insert into session_speaker (session_id, speaker_id, sort_order) values
  ('k1', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('s1', (select id from speaker where name = 'Maya Petrova'), 0),
  ('s2', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('s3', (select id from speaker where name = 'Elena Markova'), 0),
  ('s4', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('s5', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('s5', (select id from speaker where name = 'Daniela Koleva'), 1),
  ('s6', (select id from speaker where name = 'Georgi Dimitrov'), 0),
  ('s7', (select id from speaker where name = 'Daniela Koleva'), 0),
  ('s8', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('s9', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('s9', (select id from speaker where name = 'Georgi Dimitrov'), 1),
  ('s9', (select id from speaker where name = 'Stefan Petrov'), 2),
  ('s10', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('s11', (select id from speaker where name = 'Elena Markova'), 0),
  ('s12', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('s13', (select id from speaker where name = 'Georgi Dimitrov'), 0),
  ('s14', (select id from speaker where name = 'Maya Petrova'), 0),
  ('s15', (select id from speaker where name = 'Daniela Koleva'), 0),
  ('s16', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('k2', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('d2-k1', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('d2-s1', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('d2-s2', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('d2-s3', (select id from speaker where name = 'Maya Petrova'), 0),
  ('d2-s4', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('d2-s5', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('d2-s5', (select id from speaker where name = 'Daniela Koleva'), 1),
  ('d2-s6', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('d2-s7', (select id from speaker where name = 'Daniela Koleva'), 0),
  ('d2-s8', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('d2-s9', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('d2-s10', (select id from speaker where name = 'Elena Markova'), 0),
  ('d2-s11', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('d2-s12', (select id from speaker where name = 'Daniela Koleva'), 0),
  ('d2-s13', (select id from speaker where name = 'Maya Petrova'), 0),
  ('d2-s14', (select id from speaker where name = 'Elena Markova'), 0),
  ('d2-s15', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('d2-s16', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('d2-k2', (select id from speaker where name = 'Victor Stoyanov'), 0),
  ('d3-k1', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('d3-s1', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('d3-s2', (select id from speaker where name = 'Maya Petrova'), 0),
  ('d3-s3', (select id from speaker where name = 'Elena Markova'), 0),
  ('d3-s4', (select id from speaker where name = 'Maya Petrova'), 0),
  ('d3-s5', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('d3-s5', (select id from speaker where name = 'Georgi Dimitrov'), 1),
  ('d3-s6', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('d3-s7', (select id from speaker where name = 'Daniela Koleva'), 0),
  ('d3-s8', (select id from speaker where name = 'Georgi Dimitrov'), 0),
  ('d3-s9', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('d3-s9', (select id from speaker where name = 'Daniela Koleva'), 1),
  ('d3-s10', (select id from speaker where name = 'Georgi Dimitrov'), 0),
  ('d3-s11', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('d3-s12', (select id from speaker where name = 'Nikolay Ivanov'), 0),
  ('d3-s13', (select id from speaker where name = 'Elena Markova'), 0),
  ('d3-s14', (select id from speaker where name = 'Georgi Dimitrov'), 0),
  ('d3-s15', (select id from speaker where name = 'Iva Georgieva'), 0),
  ('d3-s16', (select id from speaker where name = 'Stefan Petrov'), 0),
  ('d3-k2', (select id from speaker where name = 'Venkat Subramaniam'), 0);

insert into session_material (session_id, material, sort_order) values
  ('k1', 'Slides', 0),
  ('s1', 'Slides', 0),
  ('s1', 'Repo', 1),
  ('s1', 'Reading list', 2),
  ('s2', 'Slides', 0),
  ('s3', 'Slides', 0),
  ('s3', 'Checklist', 1),
  ('s4', 'Slides', 0),
  ('s4', 'Checklist', 1),
  ('s5', 'Workshop notes', 0),
  ('s6', 'Slides', 0),
  ('s6', 'Examples', 1),
  ('s7', 'Slides', 0),
  ('s7', 'Repo', 1),
  ('s8', 'Slides', 0),
  ('s9', 'Workshop notes', 0),
  ('s9', 'Repo', 1),
  ('s10', 'Slides', 0),
  ('s10', 'Benchmarks', 1),
  ('s11', 'Slides', 0),
  ('s11', 'Examples', 1),
  ('s12', 'Slides', 0),
  ('s12', 'Checklist', 1),
  ('s13', 'Slides', 0),
  ('s13', 'Repo', 1),
  ('s14', 'Slides', 0),
  ('s15', 'Slides', 0),
  ('s15', 'Repo', 1),
  ('s16', 'Slides', 0),
  ('s16', 'Examples', 1),
  ('k2', 'Slides', 0),
  ('d2-k1', 'Slides', 0),
  ('d2-s1', 'Slides', 0),
  ('d2-s1', 'Benchmarks', 1),
  ('d2-s2', 'Slides', 0),
  ('d2-s2', 'Repo', 1),
  ('d2-s3', 'Slides', 0),
  ('d2-s3', 'Repo', 1),
  ('d2-s4', 'Slides', 0),
  ('d2-s5', 'Workshop notes', 0),
  ('d2-s5', 'Repo', 1),
  ('d2-s6', 'Slides', 0),
  ('d2-s6', 'Examples', 1),
  ('d2-s7', 'Slides', 0),
  ('d2-s8', 'Slides', 0),
  ('d2-s8', 'Checklist', 1),
  ('d2-s9', 'Workshop notes', 0),
  ('d2-s9', 'Repo', 1),
  ('d2-s10', 'Slides', 0),
  ('d2-s10', 'Checklist', 1),
  ('d2-s11', 'Slides', 0),
  ('d2-s11', 'Repo', 1),
  ('d2-s12', 'Slides', 0),
  ('d2-s13', 'Slides', 0),
  ('d2-s14', 'Slides', 0),
  ('d2-s14', 'Checklist', 1),
  ('d2-s15', 'Slides', 0),
  ('d2-s15', 'Examples', 1),
  ('d2-s16', 'Slides', 0),
  ('d2-k2', 'Slides', 0),
  ('d3-k1', 'Slides', 0),
  ('d3-s1', 'Slides', 0),
  ('d3-s1', 'Examples', 1),
  ('d3-s2', 'Slides', 0),
  ('d3-s2', 'Repo', 1),
  ('d3-s3', 'Slides', 0),
  ('d3-s3', 'Examples', 1),
  ('d3-s4', 'Slides', 0),
  ('d3-s5', 'Workshop notes', 0),
  ('d3-s5', 'Repo', 1),
  ('d3-s6', 'Slides', 0),
  ('d3-s6', 'Repo', 1),
  ('d3-s7', 'Slides', 0),
  ('d3-s7', 'Repo', 1),
  ('d3-s8', 'Slides', 0),
  ('d3-s8', 'Checklist', 1),
  ('d3-s9', 'Workshop notes', 0),
  ('d3-s10', 'Slides', 0),
  ('d3-s10', 'Checklist', 1),
  ('d3-s11', 'Slides', 0),
  ('d3-s12', 'Slides', 0),
  ('d3-s12', 'Checklist', 1),
  ('d3-s13', 'Slides', 0),
  ('d3-s14', 'Slides', 0),
  ('d3-s14', 'Examples', 1),
  ('d3-s15', 'Slides', 0),
  ('d3-s16', 'Slides', 0),
  ('d3-k2', 'Slides', 0);
