-- Real jPrime 2026 conference data mirrored from the public PWA.
-- Generated by scripts/import-jprime-data.mjs; do not hand-edit generated rows.

alter table speaker add column if not exists source_id integer;
alter table speaker add column if not exists image_url varchar(256) not null default '';

delete from notification;
delete from session;
delete from speaker_tag;
delete from speaker;
delete from map_spot;
delete from room;
delete from conference_day;

insert into conference_day (id, weekday, wd_short, date_label, short_label, calendar_date) values
  (1, 'Wednesday', 'Wed', 'June 3, 2026', 'Jun 3', date '2026-06-03'),
  (2, 'Thursday', 'Thu', 'June 4, 2026', 'Jun 4', date '2026-06-04');

insert into room (name) values
  ('Hall A'),
  ('Hall B'),
  ('Workshops'),
  ('Atrium');

insert into map_spot (name, pos_x, pos_y, kind, sort_order) values
  ('Hall A', '18%', '24%', 'stage', 0),
  ('Hall B', '63%', '24%', 'stage', 1),
  ('Workshops', '22%', '62%', 'stage', 2),
  ('Atrium', '66%', '62%', 'coffee', 3);

insert into speaker (name, role, org, location, pronoun, bio, handle, source_id, image_url) values
  ('Arnaud Jean', 'The Witcherish', '', '', '', 'Developer Advocate @ AWS

I am truly passionate about developer experience and believe that developers want simplicity, not complexity. Programming should be about solving problems and creating features that astonish users, not wrestling with frameworks.

My mantra: Helping Devs build cool stuff, learn faster, and laugh along the way — one bug at a time.

𝘈𝘭𝘭 𝘷𝘪𝘦𝘸𝘴 𝘦𝘹𝘱𝘳𝘦𝘴𝘴𝘦𝘥 𝘢𝘳𝘦 𝘮𝘺 𝘰𝘸𝘯.', '@thewitcherish', 777, 'https://jprime.io/image/speaker/777'),
  ('Cay Horstmann', 'The very same CAY HORSTMANN', '', '', '', 'After growing up in the German countryside, I studied in the United States (M.S. in computer science from Syracuse University, and a Ph.D. in mathematics from the University of Michigan in Ann Arbor). For four years, I was VP and CTO of an Internet startup that went from 3 people in a tiny office to a public company. I taught computer science at San Jose State University and held visiting appointments at universities in Germany, Switzerland, Vietnam, and Macau. In my copious spare time I write books and articles on programming languages and computer science education.', '@cayhorstmann', 677, 'https://jprime.io/image/speaker/677'),
  ('Christian Heitzmann', 'The Not-So-Neutral Swiss Guy', '', '', '', 'Christian Heitzmann, MSc ETH CSE, is the founder and owner of SimplexaCode AG, based in Lucerne, Switzerland. He is a certified software developer in Java and Python, holding teaching diplomas in both Computer Science and Mathematics, as well as a CAS in Machine Learning. With over 20 years of experience in software development and 12 years of teaching Java, Python, mathematics, and algorithms, Christian is also a regular contributor to IT journals, sharing his expertise in the field.', '', 733, 'https://jprime.io/image/speaker/733'),
  ('Emanuel Trandafir', 'Baeldung Author & Rock Climber', '', '', '', 'Hey there, I''m Emanuel - a Software Craftsman from Romania.

I value simplicity and intentionality over blindly applying patterns and abstractions.

I care deeply about the design and testability of the software I create.

I also value communication and collaboration and enjoy sharing my knowledge through open-source contributions and technical articles.', '', 775, 'https://jprime.io/image/speaker/775'),
  ('François Martin', 'The Hallway Track Engineer', '', '', '', 'François Martin is a senior full-stack software engineer at Karakun AG in Switzerland, passionate about building high-quality applications. He co-authored the open-source JavaFX frameworks WorkbenchFX and PreferencesFX, and organizes Basel''s Hackergarten to help developers get involved with open-source projects.

François is an Oracle ACE Associate and an active member of the Swiss Testing Board and ISTQB''s Advanced and Expert Working Group, co-authoring the ISTQB Test Analyst v4.0 and the upcoming Security Test Analyst syllabus. He is also part of the content committees for the BaselOne and DevBcn conferences.

François regularly speaks at international conferences, sharing insights to inspire developers and improve software quality.', '@fmartin_', 804, 'https://jprime.io/image/speaker/804'),
  ('Gerrit Grunwald', 'Java Lover', '', '', '', 'Gerrit Grunwald is a software engineer that loves coding for around 40 years already. He is a true believer in open source and he is an active member of the Java community, where he founded and leads the Java User Group Münster (Germany), he is a JavaOne rockstar and a Java Champion. He is a speaker at conferences and user groups internationally and writes for several magazines.', '@hansolo_', 5, 'https://jprime.io/image/speaker/5'),
  ('Hinse ter Schuur', 'Trade-off Juggler', '', '', '', 'Hinse is a Software Engineer at SDB Java. He has been a professional Java coder for over 20 years. He loves to share his experience by doing pair programming, reviews, writing articles and giving talks.', '@coduinix', 691, 'https://jprime.io/image/speaker/691'),
  ('Ioannis Kolaxis', 'Reinventing software engineering', '', '', '', 'Ioannis Kolaxis is a Director and a Senior Technology Architect at Accenture. He focuses on Green Software & AI innovations, helping organizations reduce the electricity consumption and operating costs of their IT workloads. He is an inventor, speaker, and author of the Green Software book.
Ioannis invented a novel way of working remotely, having filed five patents for software solutions.
He frequently speaks at conferences, like JPrime 2024, GOTO Amsterdam 2022, Devoxx Ukraine 2021 & Oracle Code One 2019.
Visit his website to learn more: https://kolaxis.dev', '@IoannisKolaxis', 326, 'https://jprime.io/image/speaker/326'),
  ('Ivan Yonkov', 'Javarchaeologist', '', '', '', 'Born to explore cutting-edge tech, but destined to support legacy software, Ivan is finding true relics, when recreating the past. And since the history is bound to repeat, his true fate is preaching Java through the fundamental concepts that are keeping the earth on their shoulders. For fifteen odd years, Ivan is combining technical trainings, software engineering and conferences all over the globe. He is the co-organizer of the ANZ conference ChurConf and is currently a Managing Partner in the software consultancy Codexio.', '', 631, 'https://jprime.io/image/speaker/631'),
  ('Johannes Bechberger', 'OpenJDK Hacker and Tools Developer', '', '', '', 'Johannes Bechberger is a JVM developer working on profilers and their underlying technology in the SapMachine team at SAP. This includes improvements to async-profiler and its ecosystem, a website to view the different JFR event types, and improvements to the FirefoxProfiler, making it usable in the Java world. His work today comprises many open-source contributions and his blog, where he regularly writes on in-depth profiling and debugging topics. He also works on hello-ebpf, the first eBPF library for Java. His most recent contribution is the new CPU Time Profiler in JDK 25.', '@parttimen3rd', 686, 'https://jprime.io/image/speaker/686'),
  ('Jonathan Vila López', 'A community advocate', '', '', '', 'International Speaker, JavaChampion, Cofounder of JBCNConf and DevBcn conferences in Barcelona, and AI4Devs conference in Amsterdam.

Currently working as a Staff Developer Advocate in Java at Sonar (SonarQube), focused on Code Quality, Dev Productivity, AI & Security.

I have worked as a (paid) developer for more than 30 years ago using multiple languajes, but for the last 15 using Java. Although I started when I was 14 with my Amstrad CPC 6128 :)

I am very interested in simulated reality, psychology, philosophy, and Java.', '@vilojona', 547, 'https://jprime.io/image/speaker/547'),
  ('Jordan Jovkov', 'Old School Java Guy, AI Geek', '', '', '', 'Jordan Jovkov is a Team Lead / Senior Software Developer.

He entered programming in 1993 and quickly realized that this would be his career passion. During high school, he was part of the school''s informatics team and took part in olympiads and competitions.

He has worked as a developer, team leader, and responsible person for certain projects. He has participated in the development and maintenance of critical projects for Bulgarian government institutions.
He has delivered lectures at DEV.BG and SoftUni. He has also been a teaching assistant at the Technical University of Sofia, as well as at the Java Academy of the Bulgarian Java User Group.

He has experience in the whole software development lifecycle. In a previous company, he was a key figure in the process of training new colleagues in the Java team. Beyond the technical aspects, he also enjoys working with people. In this regard, he has experience managing small teams, communicating with other IT departments, organizing collaboration with other IT companies, as well as installing and supporting software for clients.
He always strives to follow good practices and create quality software products.', '', 801, 'https://jprime.io/image/speaker/801'),
  ('Kevin Dubois', 'Sr Principal AI Wrangler', '', '', '', 'Kevin Dubois is a software architect and platform engineer with a career spanning over 20 years. He is often featured as a keynote speaker at conferences around the world where he shares his experience and knowledge about cloud native & AI software development, developer experience, open source and Java. Kevin is also an author and Java Champion. He currently works as a Senior Principal Developer Advocate at IBM, and is also Technical Lead for the CNCF Developer Experience Technical Advisory Group.', '@kevindubois.com', 799, 'https://jprime.io/image/speaker/799'),
  ('Kristiyan Stoyanov', 'Multi-Agent Troublemaker', '', '', '', 'Kristiyan is a Principal Engineer with over eight years of experience building and evolving large-scale backend systems in fintech and enterprise environments. He has worked extensively on complex system migrations, helping teams modernize platforms while maintaining reliability at scale.

His interests span software architecture at multiple levels — from system-wide concerns such as microservices and distributed systems, to service-level design patterns like clean and hexagonal architecture. He is particularly passionate about CI/CD, developer productivity, and using automation to reduce operational and cognitive overhead for engineering teams.

An early adopter of LLM-based systems, he focuses on how AI can be introduced into backend architectures in a practical, controlled, and production-ready way. Through his work and talks, he aims to help engineers better understand emerging architectural patterns and apply them with confidence in real-world systems.', '', 789, 'https://jprime.io/image/speaker/789'),
  ('Lyubomir Bozhinov', 'Technology Leader', '', '', '', 'Technology Leader | Bridging Strategy, Innovation & Scalable Execution', '', 792, 'https://jprime.io/image/speaker/792'),
  ('Marcin Chrost', 'A humble developer', '', '', '', 'Software engineer with over 20 years of experience and IT trainer. I have participated in many international projects and now regularly support younger colleagues in their professional development. I like novelties in the IT world, although approach them with common sense and reserve resulting from experience. What I appreciate the most, are well-coordinated and self-organizing teams that can motivate themselves. I also believe that soft skills in the IT world are as important as technical ones and are often underestimated.', '', 770, 'https://jprime.io/image/speaker/770'),
  ('Marit van Dijk', 'Developer Advocate at JetBrains', '', '', '', 'Software Developer | Java Champion | Developer Advocate at JetBrains | Open Source Enthusiast.

With 20 years of software development experience in different roles and companies, Marit loves building awesome software with amazing people and making developers lives better. She enjoys learning new things as well as sharing knowledge on programming, software development, testing & test automation, and more. She has contributed to open-source projects like Cucumber and several other projects. Marit speaks at international conferences, in webinars, and on podcasts, writes blog posts and tutorials, and contributed to the book “97 Things Every Java Programmer Should Know” (O’Reilly Media).', '@MaritvanDijk77', 603, 'https://jprime.io/image/speaker/603'),
  ('Milen Dyankov', 'The Vector Whisperer', '', '', '', 'Milen is on a mission to help software developers worldwide design clean, modular, and future-proof systems. With over 25 years of experience building distributed architectures, consulting for global tech companies and leading engineering teams, he brings a "software craftsmanship" lens to modern development. While his roots are in enterprise Java and complex systems, Milen is currently focused on navigating companies and developers through the "AI ocean" without drowning. He is dedicated to ensuring they continue building well-architected solutions rather than falling for the newest shiny products.', '@milendyankov', 9, 'https://jprime.io/image/speaker/9'),
  ('Nayden Gochev', '', '', '', '', 'Java-brewed engineer with a taste for Kotlin (Compose), a tolerance for TypeScript (React), and a soft spot for Dart + Flutter. Co-leader of jug.bg, co-organizing jprime.io, java.beer, DataStackConf and FullStackConf', '@gochev', 810, 'https://jprime.io/image/speaker/810'),
  ('Panche Chavkovski', 'JUGMK Helmsman', '', '', '', 'Panche is a Principal Software Engineer at G+D Netcetera and the current jug.mk leader.
An experienced Java developer by trade, he has a passion for IoT, 3D printing, and recently, Generative AI.
He is known as the creator of pulse.eco, a core initiator of netaville.mk, and an active contributor to the Macedonian IT community.', '', 786, 'https://jprime.io/image/speaker/786'),
  ('Piotr Przybył', 'Senior Developer Advocate', '', '', '', 'Notorious engineer at work and after hours, tracing meanders of the art of software engineering. Java Champion. Docker Captain. Testcontainers Champion. Remote Software Gardener, mostly working in web-oriented Java gardens. Programming usually in Java (since 1.3), Scala and Go, but in other languages too. Fan of agility, seen mostly as choosing the right tools and approaches after asking the right questions. Developer, trainer and conference speaker. In his talks, Piotr covers not only hardcore Java but also software architecture, computer security, and soft-skills.', '@piotrprz', 678, 'https://jprime.io/image/speaker/678'),
  ('Sergi Almar', 'Spring Sensei', '', '', '', 'Sergi is a seasoned software engineer specializing in the JVM and the Spring ecosystem. As a certified Spring instructor, he dedicates part of his time to delivering training and assisting clients in designing and implementing effective Spring solutions. Sergi is also the organizer of Spring I/O, the leading developer conference dedicated to the Spring community. In his free time, he enjoys traveling and cycling.', '@sergialmar', 807, 'https://jprime.io/image/speaker/807'),
  ('Stefan Angelov', 'The Java guy from pLoVEdiv', '', '', '', 'Architect Lead | Engineering Manager | Senior Java Developer | Public Speaker', '@cefothe', 610, 'https://jprime.io/image/speaker/610'),
  ('Thanos Stratikopoulos', 'A Java GPU Alchemist', '', '', '', 'Dr. Thanos Stratikopoulos (male) is a Research Fellow at the University of Manchester with specialization on heterogeneous architectures and reconfigurable accelerators. He has authored more than 20 research articles in the field of hardware acceleration, system software, and programming languages. Currently, his work involves heterogeneous architectures ranging from low-power devices to high-end cloud deployments. He is one of the lead developers of TornadoVM and has been part of the team for the last eight years. In addition to his core contributions to the system''s technical development, Dr. Stratikopoulos leads the project''s communication and dissemination efforts, helping to articulate its goals and advancements to both academic and industrial audiences through talks, documentation, and outreach activities.', '@thanos_str', 806, 'https://jprime.io/image/speaker/806'),
  ('Vadym Kazulkin', 'AWS Serverless geek', '', '', '', 'Vadym Kazulkin is AWS Serverless Hero and Head of Development at ip.labs based in Bonn. Vadym has been involved with the Java ecosystem for over 25 years. His focus and interests currently include the design and implementation of highly scalable and available applications in AWS Cloud with the special passion for Serverless, Generative AI and optimization of Java applications (also using SpringBoot, Micronaut and Quarkus frameworks) on AWS Lambda. Vadym is also the co-organizer of the Java User Group Bonn meetup, a frequent speaker at various meetups and conferences and a regular author of the articles in the different published magazines and on his online blog.', '@VKazulkin', 772, 'https://jprime.io/image/speaker/772'),
  ('Venkat Subramaniam', 'Programmer and Author', '', '', '', 'Dr. Venkat Subramaniam is an award-winning author, founder of Agile Developer, Inc., creator of agilelearner.com, co-founder of the devdotnext software conference, and an instructional professor at the University of Houston.

He has trained and mentored thousands of software developers in the US, Canada, Europe, and Asia, and is a regularly-invited speaker at several international conferences. Venkat helps his clients effectively apply and succeed with sustainable agile practices on their software projects.

Venkat is a (co)author of multiple technical books, including the 2007 Jolt Productivity award winning book Practices of an Agile Developer. You can find a list of his books at agiledeveloper.com. You can reach him by email at venkats@agiledeveloper.com or on twitter at @venkat_s.', '@venkat_s', 591, 'https://jprime.io/image/speaker/591'),
  ('Victor Rentea', 'The Training Guy', '', '', '', 'With 20 years of experience, Victor is an AI-Augmented Java Champion who has trained thousands of engineers from over 150 companies in a large variety of domains. The lessons learned from these sessions, he shared in countless educational talks, top-rated at major conferences, where he’s known as ‘the speaker with the soundboard’. In his spare time, Victor runs 1:1 individual coaching sessions and organizes online meetups for the European Software Crafters community. More on https://victorrentea.ro', '@victorrentea', 122, 'https://jprime.io/image/speaker/122'),
  ('Viktoriya Kutsarova', 'Redis Ecosystem Advocate', '', '', '', 'Viktoriya Kutsarova is a Senior Software Engineer at Redis on the Clients & Ecosystems team, focused on the Spring ecosystem. She works on Spring Data Redis, integrating new Redis capabilities in a Spring-native way. She holds a Master''s degree specialising in distributed systems from TU Delft and KTH Royal Institute of Technology (Stockholm). Her work bridges modern Redis features with the needs of Java and Spring developers.', '', 794, 'https://jprime.io/image/speaker/794'),
  ('Willem Jan Glerum', 'Quarkus Giant', '', '', '', 'Willem Jan is a Principal Software Engineer at Lunatech who loves building cloud software and contributing to open source. He''s all about writing quality code and finding ways to automate anything. Willem Jan has been working with Quarkus since the beginning and enjoys making sure his applications are both simple and secure. On weekends, you won''t find him behind a keyboard - he''s either out enjoying nature or volunteering with his local scout group.', '@wjglerum', 747, 'https://jprime.io/image/speaker/747');

insert into session (id, day_id, start_time, end_time, title, room_id, track, level, kind, plenary, description, status, sort_order) values
  ('44', 1, time '08:00', time '09:30', 'Registration & Coffee', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Registration & Coffee', 'upcoming', 1),
  ('45', 1, time '09:30', time '10:00', 'Opening', (select id from room where name = 'Hall A'), 'Plenary', '', 'break', true, 'Opening', 'upcoming', 2),
  ('252', 1, time '10:00', time '10:50', 'Learning modern Java the playful way', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Staying up to date with modern Java can feel overwhelming. If you don’t have any experience with Java since Java 8 (or at all), features like structured concurrency or pattern matching might sound exciting, but also scary: “How do I even get started with that?”
Fear not! In this session Marit and Piotr will explain to you the new exciting things and also show you how to use them in your IDE, so that the next day you can start having fun and profit with modern Java in your favorite tools on your own.', 'upcoming', 3),
  ('253', 1, time '10:00', time '10:50', 'Practical MCP Security in Action', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'AI Assistants need to securely authorize and access Model Context Protocol (MCP) servers to safely use imported tools, prompts and resources.

In this session, we will discuss what it takes to create a secure MCP server, explain how MCP Authorization works, and cover important security considerations.

We''ll demonstrate how an MCP client running as a Single Page Application can seamlessly use OAuth2 authorization code flow and dynamic client registration to import and access MCP servers securely.

We will also look at how MCP Clients can run in scope of a larger enterprise AI application and propagate user authentication tokens to secured MCP servers.

Throughout the session, we will work with popular MCP clients as well as the Quarkus MCP Server and Client. No prior experience of Quarkus is required.', 'upcoming', 4),
  ('47', 1, time '10:50', time '11:05', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 5),
  ('254', 1, time '11:05', time '11:55', 'Agentic AI Patterns for Enterprise Software', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Developing AI applications today isn’t just about experimental single-model interactions. Organizations are rapidly adopting AI and to do that, the requirements for enterprise software become increasingly more complex. Advanced Agentic AI systems address this need, where multiple specialized agents work together, each capable of independent reasoning.

The real challenge for architects lies in orchestrating these agents to collaborate effectively towards a common goal. Unfortunately though, "one-size-fits-all" or “off-the-shelf” approaches to coordination just don''t work due to the complex nature of software.

In this session we''ll explore the spectrum of agentic patterns, from reliable and predictable, but rigid workflows to highly flexible, autonomous agent orchestration using LLMs, and everything in between.

This talk will cover:
* The pros and cons of various agentic patterns.
* Practical demonstrations of how to combine these patterns in an enterprise software environment with Java, LangChain4j and its Quarkus extension.
* How to leverage the provided infrastructure for agent collaboration.
* The flexibility to implement and seamlessly integrate your own custom agentic patterns.', 'upcoming', 6),
  ('255', 1, time '11:05', time '11:55', 'JDK 25''s new CPU-Time Profiler', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'When your Java application is slow, you need to use a Java profiler. Before JDK 25, the built-in Java profiler only allowed you to profile based on execution time, not CPU-time, and those aren’t the same. A method blocked on I/O and a method doing tight computation can look identical… unless you have CPU-time profiling, which lets you focus on what’s truly burning your CPU.

In this talk, I’ll introduce you to the new CPU-time profiler in JDK 25 (JEP 509). You’ll learn why the traditional JFR execution profiles can mislead, how CPU-time sampling works under the hood, and how you can now profile your application more accurately without relying on potentially unsafe, external tools.

Whether you care about performance or just want to understand your app’s throughput bottlenecks, this talk by one of the minds behind the profiler will give the foundations of profiling and show you why it’s easier than ever with JDK 25.', 'upcoming', 7),
  ('50', 1, time '11:55', time '13:00', 'Lunch Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Lunch Break', 'upcoming', 8),
  ('256', 1, time '13:00', time '13:50', 'Experiment Agentic AI patterns (and MCP) within your own workloads', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Building production-grade agentic systems isn''t just about choosing the right protocols, when should agents communicate peer-to-peer versus through a supervisor?

In this talk we''ll explore design framework and implementation approaches for AI agent systems that operate autonomously while remaining controllable and aligned with your goals using Spring AI.

Whether you''re already familiar with AI agent systems or not, there will be some useful resources (i.e: code samples & live demo) to solve your own challenges. :)

For reference (patterns implemented using Spring AI): https://docs.aws.amazon.com/prescriptive-guidance/latest/agentic-ai-patterns/introduction.html', 'upcoming', 9),
  ('257', 1, time '13:00', time '13:50', 'Kotlin for Normal Brains (Without Jets)', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'An introduction to Kotlin for Java developers who just want to write in a JVM language from another universe.

We’ll look at Kotlin the way a Java developer actually experiences it:
- how Kotlin reduces boilerplate
- how null‑safety works
- how data classes, extensions, and smart casts simplify everyday tasks
- how functions, lambdas, and collections feel compared to Java
- how to migrate from Java without rewriting your world
- what Kotlin improves — and what it intentionally doesn’t change

If you’ve ever thought “Kotlin looks cool, but I don’t have time to learn a whole new ecosystem,” this session is for you.
You’ll leave with a clear, practicle understanding of Kotlin as a Java complimentary skill and not as a completely different universe.', 'upcoming', 10),
  ('260', 1, time '13:00', time '14:55', 'Human-in-the-Loop Engineering: Designing Systems Where Agents Propose, Humans Approve', (select id from room where name = 'Workshops'), 'Workshops', '', 'workshop', false, 'AI agents can write code, design systems, and make decisions. But should they act alone? In high-stakes environments, the answer is no. The most effective AI systems aren''t fully autonomous. They''re collaborative: agents propose, humans approve.

In this workshop, we''ll build human-in-the-loop systems from scratch. You''ll learn how to design approval workflows, implement strategic checkpoints, and create escalation paths that balance automation speed with human judgment. We''ll cover practical patterns for different risk levels: when to let agents run, when to pause for review, and when to require explicit approval.

Through hands-on exercises, you''ll implement HITL patterns using real tools and frameworks. By the end, you''ll have a working system where AI agents handle routine work autonomously while surfacing critical decisions to humans at the right moments.

Bring your laptop. We''re building, not just talking.', 'upcoming', 11),
  ('53', 1, time '13:50', time '14:05', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 12),
  ('258', 1, time '14:05', time '14:55', 'Scotty I need Warp Speed - Ways to improve the JVM startup/warmup', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'When running Java at scale, the JVM startup time can become a limitation. Especially when you look at spinning up new instances of an app as response to changes in load, the warmup time can be a problem. A couple of years ago you only had CDS that could help you with the startup but meanwhile there are a couple of solutions that can help you to let your JVM start super fast. These days we have AppCDS, CRaC, Native Image, Leyden, InstantOn, Ready Now, JITServer and Cloud Native Compiler, which are all solutions that help to reduce the startup time of a JVM. Each of those is not a Silver Bullet, so you have to choose the right solution for your problem.
This session will give you a short overview of the different solutions to increase your JVM startup performance and will try to give you some hints on how to choose the right solution for your application.', 'upcoming', 13),
  ('259', 1, time '14:05', time '14:55', 'Building production-ready AI Agents with Spring AI and Amazon Bedrock AgentCore', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Amazon Bedrock AgentCore enables us to deploy and operate highly capable AI agents securely, at scale. It offers infrastructure purpose-built for dynamic agent workloads, powerful tools to enhance agents, and essential controls for real-world deployment. In this talk, we''ll dive deep into various aspects of how to implement AI Agent in Java using Spring AI including using MCP Streamable HTTP Client to talk to the MCP Server with exposed tools. We''ll host our agent on Amazon Bedrock AgentCore and look at other AgentCore features like Observability (in standardized OpenTelemetry compatible format), Gateway (to securely connect to MCP-compatible tools) short and long-term Memory and Identity.', 'upcoming', 14),
  ('57', 1, time '14:55', time '15:20', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Coffee Break', 'upcoming', 15),
  ('261', 1, time '15:20', time '16:10', 'Agents With Seatbelts: Practical Ways to Keep AI Code Gen Under Control', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'In this session I will share **best practices** for using MCP setups and AI **Agents** in real development workflows 🤖. The goal is to improve both **quality** and **security**, since even with all the excitement around these tools, it’s still very easy to create confusing interactions, accidental data exposure, or Agents that trigger actions we never intended.

I will also present **reports comparing how different LLM models generate code**, showing clear differences in stability, output consistency, and the amount of guidance each model needs to avoid mistakes. Along with that, I’ll bring recent **figures showing the surprisingly low productivity gains** many teams report when adopting AI tools—often just small improvements instead of the big jumps everyone expects. We will look at why this happens: unclear prompts, weak tool design, loose permissions, and wrong assumptions about what the models can really handle.

The talk focuses on practical habits that developers can apply right away: tightening tool access, simplifying and focusing context, adding lightweight validation steps, and using safety patterns that prevent the common failures. My goal is to help teams build **more reliable, productive, and secure AI workflows**, making AI code generation a real benefit rather than a risky experiment 😅.', 'upcoming', 16),
  ('262', 1, time '15:20', time '16:10', 'Never a Null Moment with JSpecify', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Since the beginning of Java we''re used to dealing with NullPointerExceptions. We tried to prevent `null` references using project conventions and sprinkling (a lot of) annotations throughout our codebases.
But even with all this tedious work we still run into "null moments", unexpected NullPointerExceptions showing up at runtime.

One of the reasons this problem has been hard to solve is that Java never had a standard well-defined way to express nullness. Different annotation libraries and tools exist, with slightly different semantics. As a result, annotations often act more as hints than as guarantees.

JSpecify aims to change this. It''s a collaborative effort by major Java ecosystem stakeholders to define clear, consistent nullness semantics. With JSpecify, you can set default nullness per package via the `@NullMarked` annotation, making your intent explicit.
Because of this precision, JSpecify offers a solid foundation to provide null-safety in your libraries and applications.
You don’t need to annotate everything or rewrite existing code to get started. In this session you will learn what makes JSpecify different from other attempts. You''ll also discover how you can start applying JSpecify incrementally in your own production code right away.', 'upcoming', 17),
  ('265', 1, time '15:20', time '17:15', 'Concurrency Crossroads: Choosing between Reactive Programming and Virtual Threads in Quarkus', (select id from room where name = 'Workshops'), 'Workshops', '', 'workshop', false, 'Reactive programming has been the way to go for extra performance and concurrent programming, now we also have Virtual Threads (Project Loom). Which one should we choose? Can we leverage both? What''s the best approach to write high-performance non-blocking code in our application?

In this talk we''ll explain the background behind both paradigms and go over the details together. We will cover the advantages and disadvantages of both paradigms using real-world examples in Quarkus. Furthermore, we will tell you the gotchas so you don''t have to discover them yourself and we will also look ahead at what''s coming next in future Java versions.

We will aim to make this talk as simple as possible and show real code combined with live coding. After this talk you will understand both paradigms and be able to choose the right approach for your next project.', 'upcoming', 18),
  ('60', 1, time '16:10', time '16:25', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 19),
  ('263', 1, time '16:25', time '17:15', 'Observing Project Valhalla', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Project Valhalla introduces value types into the Java language and virtual machine. Value types can be more efficient since they do not need pointer indirection and heap allocation. Moreover, Valhalla will lead to a more regular object model, unifying primitive types and their boxed types, and to simpler parameterized types. In this presentation, you will learn about the present state of the project. More importantly, you will learn how to observe what Valhalla does, through JMH benchmarks, Java Flight Recorder, JITWatch, the Java Object Layout tool, and others. With that knowledge, you are ready to evaluate the impact of Valhalla on your own Java workloads.', 'upcoming', 20),
  ('264', 1, time '16:25', time '17:15', 'Automating Workflows with Multi-Agent Systems', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Using a single LLM-powered agent to handle complex workflows sounds appealing — until it starts breaking in unpredictable ways.

In this talk, we’ll explore why single-agent systems fail and how multi-agent architectures offer a more scalable and controllable alternative. We’ll introduce the concept of agents, discuss agents as tools and agent-to-agent (A2A) collaboration, and show how workflows can be modeled as coordinated agent interactions.

Using Strands as a conceptual framework, we’ll demonstrate how to design and execute an agent-based workflow, culminating in a live demo where multiple agents collaborate to solve a real task.

Attendees will leave with a practical understanding of how multi-agent systems work, when they make sense, and how to think about integrating them into real-world backend architectures.', 'upcoming', 21),
  ('65', 1, time '17:15', time '17:30', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 22),
  ('266', 1, time '17:30', time '18:20', 'Trash Talk - Exploring the JVM memory management', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'In the realm of Java programming, understanding memory management and garbage collection mechanisms cannot only be helpful for optimizing performance and resource utilization but also in general will help you to use the right garbage collector for your application. This session will be about memory allocation, object lifecycle, and garbage collection strategies within the Java Virtual Machine (JVM). Attendees will gain insights into memory allocation strategies, object retention policies, and various garbage collection algorithms like generational and concurrent collection. So when you are interested in getting more knowledge about which garbage collector to use best for your application or about memory management in the JVM, this session is for you.', 'upcoming', 23),
  ('267', 1, time '17:30', time '18:20', 'How Coding Agents Are Transforming Software Development: From Code Completion to Autonomous Feature Delivery', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Two years ago, AI tools mainly helped while you typed code: autocomplete, snippets, and small functions.
Today, AI agents can take a development task, create a plan, change many files, run checks, and produce a working solution. This shifts the developer’s role from writing code to supervising agents.
In this session, we cover the main opportunities and risks of agent-based development.
You will leave with a clear view of what happens when code generation becomes faster and cheaper—and which practices matter more to keep quality high, especially better specifications and stronger tests.', 'upcoming', 24),
  ('66', 1, time '18:20', time '18:50', 'Raffle', (select id from room where name = 'Hall A'), 'Plenary', '', 'break', true, 'Raffle', 'upcoming', 25),
  ('67', 2, time '09:00', time '10:00', 'Breakfast', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Breakfast', 'upcoming', 1),
  ('268', 2, time '10:00', time '10:50', 'Know Your Java?', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Many of us have significant experience in Java. Yet, from time to time, we get tripped up by some code that we quite did not expect to behave the way it does. In this presentation we will take a look at some of those and get a deeper understanding of the language we use everyday. In this highly interactive session, be ready to answer some questions, discuss some code behavior, and gain some in depth knowledge of the nuances in Java.', 'upcoming', 2),
  ('292', 2, time '10:00', time '10:50', 'Know Your Java? (Overflow)', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Many of us have significant experience in Java. Yet, from time to time, we get tripped up by some code that we quite did not expect to behave the way it does. In this presentation we will take a look at some of those and get a deeper understanding of the language we use everyday. In this highly interactive session, be ready to answer some questions, discuss some code behavior, and gain some in depth knowledge of the nuances in Java.', 'upcoming', 3),
  ('70', 2, time '10:50', time '11:05', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 4),
  ('270', 2, time '11:05', time '11:55', 'Building Agents with Spring AI', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Building agents that actually work, ones that plan, reason, use tools, ask clarifying questions, and collaborate with other agents, requires more than just calling an LLM in a loop. It requires understanding agentic patterns and the protocols that connect them.

In this talk, we''ll build progressively more capable AI agents using Spring AI. We''ll start with the fundamentals and tool calling. We''ll then move into agentic territory, looking at workflow patterns and building autonomous agents with recursive advisors and composable skills. Finally, we''ll cover the emerging agent protocol landscape: MCP for connecting agents to external tools and services, and A2A for enabling agents to discover and collaborate with each other.

By the end of this talk, you''ll have everything you need to build your own Claude Code-style agent.', 'upcoming', 5),
  ('287', 2, time '11:05', time '11:55', 'Visualizing the Java Concurrency API', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'With the spread of multicore processors, parallel programming has become unavoidable. That’s why the essential principles of concurrent programming are more important than ever for every developer.

Threads have the reputation of being complicated in theory, difficult to grasp in execution, and unpredictable in practice. This talk shows how the direct handling of (low-level) threads has given way to higher-level concepts such as thread pools, synchronizers, and thread-safe data structures, making parallel programming simpler, more elegant, and safer.

The unique part: all of these concepts are demonstrated with a custom application that executes real Java code and displays how it runs in real time. You will see real and virtual threads, locks, executors, and the fork/join framework literally come alive on screen – colored, moving, and interacting – so that you can experience concurrency as never before. For many, this will be the first time the inner workings of Java’s Concurrency API become clear and tangible.', 'upcoming', 6),
  ('272', 2, time '11:05', time '11:55', 'Wnen Greed is Good--A Deep Dive into Java Stream Performance', (select id from room where name = 'Workshops'), 'Workshops', '', 'workshop', false, 'Java programmers love using streams, but what about performance? In this deep dive, you will learn how streams actually work, and when you should worry about suboptimal performance. Through debugging, profiling, benchmarking, and flight recording, we will gain insight into the internals of the stream pipeline. As one example, you will see when it makes a difference for a gatherer to be greedy. Upon completion, you will know which aspects of streams are performance-sensitive, and how to measure your own stream code.', 'upcoming', 7),
  ('74', 2, time '11:55', time '13:00', 'Lunch Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Lunch Break', 'upcoming', 8),
  ('273', 2, time '13:00', time '13:50', 'Java and GenAI: from basics to enterprise', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Java GenAI libraries are getting more mature every day. It is now incredibly easy to spin up a Spring AI "Hello World" example and connect your code to models like GPT or Gemini with just a few lines of configuration. While these "magical" setups are excellent for quick prototypes, they often hide away the control and reliability needed for real-world business needs.

This session addresses the gap between those basic demos and enterprise-friendly implementations. We will look at how to move past the default configurations and take full control of the execution flow. The goal is to ensure that it''s your application and not the LLM in the driver''s seat, allowing for better observability and predictable behavior when the AI interacts with your internal data and tools.

Finally, we will tackle the essential requirements for production: Security, Identity, and Human-In-The-Loop (HITL) workflows. We will explore how to secure the Model Context Protocol (MCP) so your tools are identity-aware, and discuss strategies to validate risky operations, ensuring that high-stakes actions are verified by a human before execution.', 'upcoming', 9),
  ('288', 2, time '13:00', time '13:50', 'My code is faster than yours... let me prove it to you!', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'You stare at the notification on your screen, your heart sinking with each passing second. It is a pull request from your colleague, Lisa, asking you to review her code. You take a deep breath and click on the link, hoping for a smooth review process. Little did you know, this simple task would soon turn into a daunting challenge.

As you scan through the code, one particular line catches your attention - a regular expression. Immediately, you knew this was a problem waiting to happen. You leave a comment on the pull request, expressing your concerns about the regex. You point out that it is not only slow but also difficult to read and maintain. You suggest Lisa replace it with a more explicit block of code that achieves the same result, albeit at the cost of increased length.

Within minutes, Lisa responded to your comment, refusing to make any changes. She argues her regex is not only shorter but also just as easy to understand. She challenges you, stating she wouldn''t change it unless you could prove your proposed solution was faster.

Your panic levels begin to rise. You have never done any performance comparisons before. You desperately search through your bookmarks, hoping to find something that could help you in this predicament. Then it strikes you - you remember that François Martin will give a conference talk showing how to do microbenchmarking in Java using JMH, scheduled to take place in just a few days. It was like a lifeline was thrown to you. With renewed hope, you quickly register for the conference, eager to gain the knowledge you need to save this code review. You sigh with relief, marking the talk''s date in your calendar with a red pen and counting down the days until the conference...', 'upcoming', 10),
  ('277', 2, time '13:00', time '14:55', 'Create Your Own Role-Playing Game with Agentic AI using Spring AI', (select id from room where name = 'Workshops'), 'Workshops', '', 'workshop', false, 'Come code a Game Master (GM) that will be responsible for orchestrating multiple AI agents, each specialized in a particular task.

We''ll explore concepts like agent tools, the MCP protocol (Model Context Protocol), A2A (Agent to Agent), and RAG (Retrieval-augmented generation) to create agents and/or MCP servers that roll dice, verify DnD rules, and generate the story as it unfolds.

Whether you''re a role-playing game fan or not, there will be things to learn during this workshop :)', 'upcoming', 11),
  ('77', 2, time '13:50', time '14:05', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 12),
  ('275', 2, time '14:05', time '14:55', 'From JVM to GPUs: Building GPU-Accelerated AI Libraries in Java with TornadoVM', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'As Java enters the AI era, developers seek ways to run high-performance machine learning workloads without leaving the JVM. This session shares lessons learnt from building GPU-accelerated AI libraries natively in Java using TornadoVM, a framework that transparently offloads Java programs to GPUs and other accelerators. Using GPULlama3.java, a GPU-accelerated library for large language models (LLMs), the session explores techniques for supporting quantized data types (FP16, Q8, Q4), integrating with Quarkus and LangChain4J, and optimizing AI inference directly in Java. Attendees will gain practical insights into how TornadoVM complements Project Babylon and Project Panama in advancing Java as a first-class platform for AI development.', 'upcoming', 13),
  ('289', 2, time '14:05', time '14:55', 'Stream Gatherers - let''s get to know each other better !', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'The concept of Stream Gatherers introduced as a permanent feature in JDK 24 naturally complements what was missing in the Java Stream API and is the biggest revolution in this area since JDK 8. It is therefore worth familiarizing yourself with the possibilities offered by this solution (and there are quite a few of them!) to be able to increase the flexibility and readability of the code related to stream processing of data structures. During the session, we will try to solve several business problems, both using already built-in gatherers, as well as creating our own.', 'upcoming', 14),
  ('82', 2, time '14:55', time '15:20', 'Coffee Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Coffee Break', 'upcoming', 15),
  ('278', 2, time '15:20', time '16:10', 'Virtual Threads Are Not Async I/O: Lessons from Operating System Archaeology', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Asynchronous programming is often presented as a modern invention - reactive streams, CompletableFuture, and now virtual threads promise scalable, non-blocking execution with minimal effort. But the underlying ideas are far older than the JVM.

In this talk, we will take an archaeological journey back to the nostalgical era of the Java roots, exploring OVERLAPPED I/O and the transition to I/O Completion Ports (IOCP). By examining how asynchronous I/O was implemented at the operating system level - long before futures and reactive APIs - we will expose the fundamental mechanics that still govern today’s Java applications.

The goal of this talk beside some nostalgia, is clarity. By understanding what the JVM actually does under the hood - and what it cannot change - we can make better architectural decisions, debug async issues more effectively, and stop treating "async" as magic.

Async didn’t get easier. It just got better disguised. And sometimes slightly misleading.', 'upcoming', 16),
  ('290', 2, time '15:20', time '16:10', 'Spring Data Redis Beyond Key-Value', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'Spring Data Redis has evolved far beyond a simple key-value abstraction, becoming a critical integration layer for modern Redis use cases. This talk highlights recent and ongoing community contributions to Spring Data Redis, showing how it''s expanding to support advanced data structures, richer querying, and a smoother developer experience. We''ll look at architectural improvements, emerging support for Redis query engines and JSON, and what these efforts mean for the future of Redis integration in the Spring ecosystem.', 'upcoming', 17),
  ('282', 2, time '15:20', time '17:15', 'Implementing Agentic RAG using Spring AI', (select id from room where name = 'Workshops'), 'Workshops', '', 'workshop', false, 'For the last two years, the RAG (Retrieval-Augmented Generation) concept has become increasingly popular by combining the power of LLMs with the ability to build AI systems that operate over specific enterprise knowledge bases. However, Naive RAG architectures have limitations and in many cases are not as effective as they could be. One of the most well-known optimization strategies to address this is Agentic RAG.

Through live coding with Spring AI 2 and Spring Boot 4, we''ll build an Agentic RAG system as an extension of a running production application Video Production Store. The system will be able to autonomously decide when and how to gather needed information from different data sources - vector or relational databases.

The process will follow these incremental steps for continuous software development.

Step 1: We''ll create a Naive RAG by implementing the RAG ETL pipeline, then implement the Retrieve, Augment, and Generation phases following best practices of separation of concerns and layered architecture.

Step 2: Once we''ve verified that our Naive RAG works well, we''ll transform it into an Agentic RAG by adding an agent in the Retrieval phase. This agent will make intelligent decisions about which data source to query - the vector database for technical knowledge or the relational database.

Step 3: We''ll evolve the system into a distributed architecture by integrating directly with the production application via a dedicated REST client library.

Step 4: We''ll evolve the system to integrate with an MCP (Model Context Protocol) server. Instead of using local tools for data retrieval, the agent will communicate with a dedicated MCP server to gather the needed data.

The workshop follows an incremental live-coding format. At the start, the completed project will be demonstrated so the direction is clear from the beginning. Due to time constraints, some code will be written together while other fragments will be copied from prepared checkpoints and explained in detail. Particular attention will be paid to how the change of specific technical parameters or strategies will affect the quality of the final result.

For a detailed step-by-step description of the workshop structure, including project architecture, technology stack, and development steps, download the full Workshop Guide.
https://drive.google.com/file/d/1IzMERN0Gr3_Eufgje6scYydUHEmUS_5Q/view', 'upcoming', 18),
  ('85', 2, time '16:10', time '16:25', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 19),
  ('280', 2, time '16:25', time '17:15', 'Beyond the LLM API - What Developers Actually Need to Know About ML', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'Once, being a software developer required being a mathematician. As our ecosystem evolved, the field opened to a generation of problem-solvers who didn''t need calculus to build world-class systems. Today, the AI revolution has polarized the field once again: separating those who understand complex math from those who simply call black-box APIs. But to build truly scalable, cost-effective, and performant enterprise applications, we cannot rely on "magic" alone. As the old engineering adage goes: you must understand at least two layers of abstraction below the one you are currently working in.

This session bridges the gap between high-level prompt engineering and deep-dive data science by focusing on the architectural fundamentals of AI. We will demystify what models actually are as software artifacts, how they differ, and how they are executed via inference runtimes. You will learn to look at models through the lens of an engineer rather than a researcher, gaining the vocabulary to collaborate with data scientists and the technical depth to move beyond the API wrapper.', 'upcoming', 20),
  ('293', 2, time '16:25', time '17:15', 'Consistency and Coordination Patterns in Event-Driven Architecture', (select id from room where name = 'Hall B'), 'Hall B', '', 'lecture', false, 'AI can help, but we’re still the ones accountable for architectural decisions that can lead to lost messages, duplicates, and other data inconsistencies.

In this session, we’ll tackle the dual-write problem, explore the Saga pattern, and compare orchestration vs. choreography strategies for managing distributed workflows.
We’ll also dive into the Transactional Outbox and Inbox patterns, showing how we can achieve at-least-once delivery and build idempotent consumers that make our event-driven microservices more resilient, consistent, and reliable.

Target Audience
- Backend engineers building event-driven microservices with Spring and dealing with data consistency, messaging, and distributed workflows
- Junior and mid-level developers who want to understand the challenges of keeping distributed systems in sync
- Architects and tech leads responsible for designing reliable distributed systems

Key Takeaways
- How can we handle common challenges such as dual writes, lost, out-of-order, and duplicate messages
- How to choose between orchestration, choreography, both, or neither
- When and how to apply Sagas, Transactional Outbox, and Inbox patterns, including their trade-offs', 'upcoming', 21),
  ('89', 2, time '17:15', time '17:30', 'Break', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Break', 'upcoming', 22),
  ('283', 2, time '17:30', time '18:20', 'Agentic Coding - Patterns and Anti-Patterns', (select id from room where name = 'Hall A'), 'Hall A', '', 'lecture', false, 'I was an AI skeptic. Like a respectable engineer who spent decades practicing the craft, I laughed at vibe coders, prompt engineers, Cursor, Claude, and the entire wave of AI “hype”. I waited for it to pass. But I was wrong. AI fundamentally changed our profession forever. This talk reviews the key practices of professional AI-first software engineers: prompt/context engineering, MCP tools, agentic design and orchestration, AI SecOps and architecture observability.

This is not a hype talk, nor a doom talk - it''s a field report from the middle of the shift already happening around us. The game is changing. The question is not whether we like it, but whether we are ready to adapt to stay relevant.', 'upcoming', 23),
  ('92', 2, time '18:20', time '18:30', 'Closing', (select id from room where name = 'Hall A'), 'Plenary', '', 'break', true, 'Closing', 'upcoming', 24),
  ('93', 2, time '18:30', time '21:00', 'Beer & Networking', (select id from room where name = 'Atrium'), 'Plenary', '', 'break', true, 'Beer & Networking', 'upcoming', 25);

insert into session_speaker (session_id, speaker_id, sort_order) values
  ('252', (select id from speaker where name = 'Piotr Przybył'), 0),
  ('252', (select id from speaker where name = 'Marit van Dijk'), 1),
  ('253', (select id from speaker where name = 'Willem Jan Glerum'), 0),
  ('254', (select id from speaker where name = 'Kevin Dubois'), 0),
  ('255', (select id from speaker where name = 'Johannes Bechberger'), 0),
  ('256', (select id from speaker where name = 'Arnaud Jean'), 0),
  ('257', (select id from speaker where name = 'Nayden Gochev'), 0),
  ('260', (select id from speaker where name = 'Lyubomir Bozhinov'), 0),
  ('260', (select id from speaker where name = 'Stefan Angelov'), 1),
  ('258', (select id from speaker where name = 'Gerrit Grunwald'), 0),
  ('259', (select id from speaker where name = 'Vadym Kazulkin'), 0),
  ('261', (select id from speaker where name = 'Jonathan Vila López'), 0),
  ('262', (select id from speaker where name = 'Hinse ter Schuur'), 0),
  ('265', (select id from speaker where name = 'Willem Jan Glerum'), 0),
  ('263', (select id from speaker where name = 'Cay Horstmann'), 0),
  ('264', (select id from speaker where name = 'Kristiyan Stoyanov'), 0),
  ('266', (select id from speaker where name = 'Gerrit Grunwald'), 0),
  ('267', (select id from speaker where name = 'Ioannis Kolaxis'), 0),
  ('268', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('292', (select id from speaker where name = 'Venkat Subramaniam'), 0),
  ('270', (select id from speaker where name = 'Sergi Almar'), 0),
  ('287', (select id from speaker where name = 'Christian Heitzmann'), 0),
  ('272', (select id from speaker where name = 'Cay Horstmann'), 0),
  ('273', (select id from speaker where name = 'Panche Chavkovski'), 0),
  ('288', (select id from speaker where name = 'François Martin'), 0),
  ('277', (select id from speaker where name = 'Arnaud Jean'), 0),
  ('275', (select id from speaker where name = 'Thanos Stratikopoulos'), 0),
  ('289', (select id from speaker where name = 'Marcin Chrost'), 0),
  ('278', (select id from speaker where name = 'Ivan Yonkov'), 0),
  ('290', (select id from speaker where name = 'Viktoriya Kutsarova'), 0),
  ('282', (select id from speaker where name = 'Jordan Jovkov'), 0),
  ('280', (select id from speaker where name = 'Milen Dyankov'), 0),
  ('293', (select id from speaker where name = 'Emanuel Trandafir'), 0),
  ('283', (select id from speaker where name = 'Victor Rentea'), 0);

